enable_audio_bell no
allow_remote_control no

font_size 9.35
#colorsceme

background #1e1e1e
foreground #e5e5e5

selection_background #2a2a2a
selection_foreground #ffffff

cursor #d3cfcf
cursor_text_color #1e1e1e

color0  #1e1e1e
color1  #d16969
color2  #6a9955
color3  #d7ba7d
color4  #569cd6
color5  #c586c0
color6  #4ec9b0
color7  #d3cfcf
color8  #6b7280
color9  #e88388
color10 #8ccf7e
color11 #e5c07b
color12 #7aa2f7
color13 #d291e4
color14 #5fd7c7
color15 #ffffff

#keymaps
map ctrl+shift+left no_op
map ctrl+shift+right no_op


# BEGIN_KITTY_FONTS
font_family      family="Adwaita Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
